### ISSUE TITLE
Убрать отрицание из условий

### ISSUE THREAD

**Issue by Frolikow** [dindeni/slider#10]
В подобных местах отрицание в условии создает дополнительную смысловую нагрузку: 
```js
let coordinatesItems;
!vertical ? coordinatesItems = (stepCount / (max - min)) * trackWidth
   : coordinatesItems = (stepCount / (max - min))
          * height;
coordinatesItems = Number(coordinatesItems.toFixed(2));
```
здесь ряд исправлений предлагаю:

1) вместо `!vertical` писать `vertical`, при этом поменять местами выражения в тернарнике.

2) зачем  объявление переменной писать отдельно? можно ведь 
```js
const coordinatesItems = condition ? expression1 : expression2;
```
обрати внимание что мы сразу делаем `const` вместо `let`

3) от последней строки тоже можно избавиться 
```js
const coordinatesItems = condition ? Number(expression1.toFixed(2)) : Number(expression2.toFixed(2));
```

4) плюс ко всему - здесь есть дублирование `(stepCount / (max - min)`, мб стоит вынести в отдельную переменную

Проверь подобные места по всему проекту.

**Comment by Frolikow** [comment]
по второму пункту еще остались подобные места
![image](https://user-images.githubusercontent.com/25764783/73328806-b011cd00-428d-11ea-95d5-b254a3ec9033.png)
![image](https://user-images.githubusercontent.com/25764783/73328816-b7d17180-428d-11ea-8210-93cbceb03f89.png)
чтобы легче было найти все моменты, попробуй сделать глобальный поиск в  проекте по слову `let`. Ты увидишь все переменные созданные с помощью этого слова, и в большинстве случаев ты их так же мутируешь, а следовательно так же можешь переписать на `const`

**Comment by dindeni** [comment]
![Screenshot from 2020-01-29 19-35-00](https://user-images.githubusercontent.com/25766511/73371534-41556380-42cf-11ea-9e05-8f68ec489e88.png)
Вот в подобном месте у меня переменная через let, потому что у меня не будет доступа за пределами if, если объявить ее через const внутри. Я только вижу вариант делать внутреннюю функцию в подобных местах, чтобы использовать const. Но у меня сомнения стоит ли плодить столько функций?
Подобное решение:
![Screenshot from 2020-01-29 20-00-28](https://user-images.githubusercontent.com/25766511/73373475-1e787e80-42d2-11ea-8299-2a511e56cdfb.png)

**Comment by Frolikow** [comment]
Я считаю, что лучше лишняя функция, чем лишняя мутация)

**Comment by dindeni** [comment]
Вроде все поправил, остались только где без них не обойтись и у флагов.
