### ISSUE TITLE
Замечания по архитектуре

### ISSUE THREAD

**Issue by Sergio-Ka** [dindeni/slider#15]
Думаю стоит перечитать данную статью:
https://habr.com/ru/post/321050/
Модель явно из себя не представляет ничего, а контроллер явно ТТУК (в терминах статьи). Поэтому необходимо будет переделать.

**Comment by Sergio-Ka** [comment]
1. Наблюдатель - сущность абстрактная и никаких подробностей реализации того, с чем он работает он знать не должен. Должна быть возможность выдрать его из этого проекта и вставить в другой без переделок. Есть общие методы подписки, отписки и уведомления. Если какая-то сущность хочет знать какое-то конкретное событие, на которое она будет реагировать - она на него и подписывается подсовывая свой метод. В этой связи метод notifyAllForScale выглядит странно.
2. Там же параметр value не протипизирован. Там вообще возможно стоит для data описать интерфейс выше или type alias. И зачем-то два интерфейса при этом один от другого наследуется, с учетом того что там в каждом по одному полую - это тоже мне кажется выглядит странно, можно оптимальнее и короче написать.
3. И вообще сам метод notifyAll реализован как-то странно. Он почему-то возвращает зачем-то число, хотя по хорошем должен быть void, а внутри вызывать в зависимости от типа события те методы которые записаны в observers по ключу этого события. Это как вариант возможный реализации.
4. Кроме вышеописанного я не вижу чтобы метод notifyAll вызывался в модели. А должен исходя из того что модель - независимая часть приложения, которая содержит логику. То есть в данном случае предположительно: начало слайдра, конец слайдера в абстрактных единица, положение ползунков плюс методы валидации всего этого. В нее контроллер передает информацию используя ее публичный интерфейс, а она провалидировав ее эту инфу и изменив, должна оповестить все заинтересованные сущности (здесь - контроллер), что она изменилась. и делается это как раз с помощью метода notifyAll.
5. То же самое для вьюхи. Она шлет уведомления всем заинтересованным сущностям (опять таки контроллер в данном случае) при воздействии на нее пользователя и предоставляет публичный интерфейс для окружения (набор методов), например в данном случае для контроллера, который эксплуатируя его заставляет ее изменяться.
6. В данном кстати случае, не смотря на то, что контроллер знает о вьюхе, будет лучше если он не будет шарить во всех подклассах вьюхи как сейчас, а будет обращаться к главному вью, как к фасаду (паттерн), а уже главный вью будет распределять работу по своим остальным классам. А лучше это потому что связанность лишняя не нужна , чем меньше сущности переплетены между собой и меньше друг от друга зависят, тем лучше с точки зрения переиспользвания кода и дальнейшего развития проекта.
7. С учетом вышеописанного может показаться что контроллеру тогда особо и делать нечего. От части так и есть. Но контроллер может взять на себя следующие роли:
- точка входа в приложение (не так как сейчас - плагинная часть лезет в модель передавая ей начальные данные; тут опять по той же причине -связанность будет ниже)
- там могут происходить подписки сущностей
- могут создаваться инстансы сущностей (хотя возможно и в плагинной части).
Тогда контроллер будет тонким.
8. В плагинной части это можно упразднить (function ($): void {...}(jQuery)); потому что IIFE тут ни к чему, так как тут и так модуль. Если не ясно о чем речь - изучить вопрос по IIFE и для чего оно надо - все равно на втором джуне сдавать придется.
9. так же из каши-малаши в demo  с первого взгляда не совсем ясно как происходит обмен данными между плагином и демо страницей (панелью управления). От сюда следует несколько выводов - код в демо сумбурный и его неплохо бы несколько упростить, причесать и оптимизировать. И совсем не обязательно чтобы демостраница делала какую-то особую валидацию, так как ее уже и так по хорошему делает модель. Но тут надосмотреть. И второй - именования и кодстайл. Вот такие штуки конечно прикольно const validation = {
      checkRangeValue: (): number | undefined => {..., но по хорошему их нужно делать было двумя методами и тогда твоя константа validation при задании ей значения выглядела бы лучше и лучше читалась и воспринималась.
На счет обмена данными между демостраницей-панелью и непосредственно плагином, намекну что тут тут так же можно использовать паттерн наблюдатель. Или передавать колбек в качестве параметра.

Вообще сразу все усмотреть сложно и лучше итеративный подход к проверке, так как многое будет зависеть от того, как будут решены эти девять вопросов.

**Comment by dindeni** [comment]
В demo слайдер только инициализируется, с методами слайдера взаимодействия нет у demo, чтобы эти две части не влияли друг на друга. Все данные для своей работы demo берет из разметки. Или нужно сделать именно взаимодействие между плагином и demo страницей?

Насчет валидации, там именно дополнительные проверки для  инпутов и сообщения при вводе неверных данных, но можно это все убрать, если нужно.

**Comment by dindeni** [comment]
Теперь demo взаимодействует с плагином через контроллер и берет оттуда данные для обновлений, использовать подписки мне кажется не смысла, так как данные можно получить через свойство контроллера.
Валидацию я все таки оставил потому, что там проверяются именно свойства инпутов и при некорректных данных свойств вызываются сообщения с ошибками.

**Comment by Sergio-Ka** [comment]
Привет. Я с 5 марта не работаю в FSD, поэтому с вопросами по дальнейшей доделке тебе надо просигналить в чат 5го задания и попросить назначить тебе ревьюера. Хотя я перед уходом это и так делал, но возможно люди тебя потеряли. И вообще не стесняйся почаще писать, задалбливать не надо конечно, но если тебя за 3-4 дня никто не посмотрел - надо писать. Если в чате не отвечают - пиши Сергею напрямую или кто там у тебя в контактах.

**Comment by Sergio-Ka** [comment]
>  demo взаимодействует с плагином через контроллер и берет оттуда данные для обновлений

Если честно, то адекватного способа это сделать я еще не видел (а человек я проверил много), поэтому сомневаюсь что там у тебя нормально в этом плане.

> Все данные для своей работы demo берет из разметки

Если реализовано так, то это вообще жесть. Ты привязываешься к структуре, а она изменчива крайне. Это во-первых, а во-вторых ты смешиваешь зоны ответственности - разметка и оформление это одно, а данные и работа с ними с помощью JS другое. Ты обрекаешь себя на больс дальнейшей поддержкой и развитием проекта. Понятно что здесь проект скорее всего не будет развиваться. Ну так у тебя и не такая задача здесь. Ты должен научиться на простом примере делать нормально.
