### ISSUE TITLE
Ошибки в работе слайдера

### ISSUE THREAD

**Issue by imin314** [dindeni/slider#18]
1) Закрашенная область выделяется сейчас наоборот:
![Выделение_429](https://user-images.githubusercontent.com/40715953/84770149-41959780-b001-11ea-9208-7d2b74edef85.png)

2) Поле step должно быть доступно вне зависимости от наличия шкалы:
![Peek 2020-06-16 18-51](https://user-images.githubusercontent.com/40715953/84770806-70603d80-b002-11ea-83dd-3e8fef4fdf84.gif)

3) Бегунок выходит за пределы полоски слайдера справа:
![Peek 2020-06-16 18-53](https://user-images.githubusercontent.com/40715953/84770916-a9001700-b002-11ea-9b62-eb8b5251148d.gif)

4) Эти два пункта из требований на риззоме не выполнены (шкала должна быть интерактивной, а слайдер - отзывчивым (по горизонтали).
![image](https://user-images.githubusercontent.com/40715953/84771299-5ffc9280-b003-11ea-8a7e-8298b313bf0c.png)

**Comment by imin314** [comment]
Остались еще некоторые баги:

1) Если ввести значение второго бегунка меньше первого, то бегунок перемещается:
![Peek 2020-08-06 15-34](https://user-images.githubusercontent.com/40715953/89511018-8b2d8200-d7fb-11ea-850d-cc67c7cde405.gif)

2) В горизонтальном слайдере как-то странно работает интерактивная шкала - бегунки передвигаются не на то значение.
![Peek 2020-08-06 15-42](https://user-images.githubusercontent.com/40715953/89511099-a6988d00-d7fb-11ea-8628-71e5d7f25d6b.gif)

**Comment by dindeni** [comment]
Вроде больше не появляется такое

**Comment by SigidinIlya** [comment]
При наведении на tooltip, cursor pointer есть, но перетаскивание не работает, нужно поправить.

![cursorPointer](https://user-images.githubusercontent.com/70949093/93722332-b0edcb00-fb9e-11ea-945e-a9ca4d32d048.gif)

Если какие-то toggler'ы имеют состояние disabled, то лучше это как-то стилистически обозначить, ибо в данном случае помимо этого ещё и cursor: pointer имеется)

![disabledLabel](https://user-images.githubusercontent.com/70949093/93722583-93b9fc00-fba0-11ea-828b-a4aec7f4cefe.gif)

**Comment by dindeni** [comment]
Во втором замечании: там был баг, должны быть все активны. Исправлено.

**Comment by SigidinIlya** [comment]
Да, в целом норм, ещё небольшая деталь, если установить значение которое не помещается в тултип, оно выезжает за его края.
![за пределами](https://user-images.githubusercontent.com/70949093/96189404-18eac380-0f49-11eb-89ab-efba87c48d85.gif)

**Comment by SigidinIlya** [comment]
посмотрел на демке, так же сделал pull из репо, всё равно выходит за границы
![image](https://user-images.githubusercontent.com/70949093/97919950-b88dbb80-1d69-11eb-9bf9-5592bb00f291.png)

**Comment by SigidinIlya** [comment]
Тут багулина обнаружилась...

![багулина](https://user-images.githubusercontent.com/70949093/101810864-570bfa00-3b2a-11eb-9eae-05dea1b5b4b5.gif)

**Comment by mglknFSD** [comment]
Привет, я твой новый ревьювер!

По условию задания "размер шага может быть любым"

![step](https://user-images.githubusercontent.com/75975369/103153213-08a06180-47a0-11eb-8cae-c1167cc64386.png)

Но в твоем слайдере я не могу установить размер слайдера меньше 1-цы
![степ](https://user-images.githubusercontent.com/75975369/103153246-41d8d180-47a0-11eb-9b73-63dd9cdae7f4.png)

**Comment by mglknFSD** [comment]
Не с первого раза у меня все же получилось, но точность значений оставляет желать лучшего

![step](https://user-images.githubusercontent.com/75975369/103153312-cdeaf900-47a0-11eb-865e-07dfa62cadfc.png)

**Comment by mglknFSD** [comment]
Видео с воспроизведением бага из первого сообщения


https://user-images.githubusercontent.com/75975369/103153753-ce38c380-47a3-11eb-87a5-c06914bfbeaa.mp4

**Comment by mglknFSD** [comment]
Без шкалы слайдер игнорирует величину step.


https://user-images.githubusercontent.com/75975369/103205005-9ea3cb80-4909-11eb-948f-9bb722fa5d9b.mp4

**Comment by mglknFSD** [comment]
Так же странное поведение с "перекидыванием" управления с одного элемента на другой.


https://user-images.githubusercontent.com/75975369/103205216-238ee500-490a-11eb-8218-43f310e743b2.mp4

**Comment by mglknFSD** [comment]
При переключении на vertical, положение слайдера смещается влево.

https://user-images.githubusercontent.com/75975369/104164939-bd29bc80-5409-11eb-97e7-ee7f068f59ce.mp4
