### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by Frolikow** [dindeni/slider#2]
1) Если взяться за ползунок и тащить его - то все ок, но, как только курсор уводишь за пределы шкалы - сразу останавливается ползунок. И в это время можно спокойно сделать маусАп, но с ползунка при этом не снимется маусДаун. 
1.1) на последних двух слайдерах (где шаг большой) вообще поведение очень странное(из-за ошибки из пункта 1). 
2) Нужно добавить функционал, при котором при клике по шкале, ползунок перемещался к месту клика.
3) Здесь явный баг: 
![image](https://user-images.githubusercontent.com/25764783/68088204-41d88c80-fe8f-11e9-9f33-e52b5745665a.png)
`value min` не может быть больше `value max`. При чем я такого достиг лишь ползунками, там продумать чтоб и инпуты нельзя было записать некорректное число
4) на шкалу чисел, лучше добавить ограничение, чтобы не было подобного поведения 
![image](https://user-images.githubusercontent.com/25764783/68088250-97ad3480-fe8f-11e9-9363-cfc4e818a717.png)
5) зачем инпуты с true/false? для этого ведь идеально подходит checkbox ) 
6) и здесь не понял с `undefined`'ом. Зачем ? Если это для того чтобы скрыть шкалу, то опять же, сделай отображение шкалы по чекбоксу, 
![image](https://user-images.githubusercontent.com/25764783/68088282-17d39a00-fe90-11e9-9b46-d587808420b6.png)
7) зачем писать на инпутах max(**number**)? интересует именно `number`. Почему не задать числовой инпут? зачем эти трудности конечному пользователю

**Comment by Frolikow** [comment]
1. ok
2. ok
3. частично сделал. баг не удален. в поле `value min`, по прежнему можно внести число больше `value max` и слайдер его съест
![image](https://user-images.githubusercontent.com/25764783/69011773-9821f100-09a0-11ea-803a-797d01be44e6.png)
4. что-то странное сделал, если слайдер от 0 до 100 то минимальный шаг я могу сделать 17? а если мне надо 5?)
Мб я не достаточно ясно выразился, но ограничение надо именно на шкалу сделать, не на возможные шаги, а на отображаемые числа под слайдером) тут скорее всего надо будет какую-то проверку сделать, которая будет чекать сколько чисел под слайдером, и если выше условной "нормы", то расставлять например на каждый 2-ой или 3-ий шаг) 
5. ок
6. ок
7. ок
8. почему при клике чекбоксов слайдер сбрасывается на начальные значения? 
9. если ползунок сдвигать резким движением, то шкала прогресса не поспевает за ним 
![image](https://user-images.githubusercontent.com/25764783/69012055-d967d000-09a3-11ea-84d2-0197db5730da.png)
10. при таких настройках ползунок не слабо вылетает со шкалы
![image](https://user-images.githubusercontent.com/25764783/69012073-103de600-09a4-11ea-9341-571a5730b287.png)
- тут сразу поясню как должно быть. слайдер должен делать полный шаг от 1 до 401 ( в соответствии с настройками) и потом оставшиеся 99 должны маленьким шагом быть. Если не понял - смело спрашивай

**Comment by Frolikow** [comment]
Сборка крашится, ts ругается на многие места. 

Если у тебя vsCode попробуй установить расширение TSLint, сразу будешь видеть где ошибки
![image](https://user-images.githubusercontent.com/25764783/69655692-b2975100-10a9-11ea-8eaa-06fdd75180e5.png)

**Comment by dindeni** [comment]
Теперь не должно быть ошибок.

**Comment by Frolikow** [comment]
1 (3). ок, добавил подсказку) я почему-то думал что задать аттрибутом для инпута - лучше будет) 
2 (4). ок
3 (8). ок
4 (9). ок
5 (10). в целом правильно, но если взять такие же настройки, то с 500 на 401 вернуться - несколько криво, значение ведь должно изменятся когда ты перемещаешь курсор через середину между соседними значениями) т.е. тебе нужно вычислить расстояние между 401 и 500(в данном случае) и делать расчет учитывая эту величину


с такими настройками нечто странное произошло
![image](https://user-images.githubusercontent.com/25764783/69918763-9f6cf280-14a8-11ea-8d64-716975b9a5f8.png)

и еще давай между лейблами и инпутами сократим отступ?)

я надеюсь, что по внешнему виду  - последние правки)

**Comment by Frolikow** [comment]
предыдущие замечания - все ок)

новые:
1) если слайдер задан от 100 до 500, значения ползунков выставить 499 и 500, а потом переделать слайдер от 100 до 120, то оба ползунка слипаются в вместе на значении 120 и не двигается ни один из них (только кликом по шкале возможно) 
![image](https://user-images.githubusercontent.com/25764783/70458694-3824f300-1ae5-11ea-9df8-35082d7fd404.png)
2) когда слайдер вертикальный, и большое число возможных значений, то ползунки ни как не получается придвинуть один к другому

**Comment by Frolikow** [comment]
1. Получилось частично. Если подобные условия создать на минимальной границе - получим такой же баг
2. Не заметил изменений в работе плагина. Вообще что-то странное опять происходит со слайдером. 
Пример: на втором слайдере не меняя настроек, поднимаем второй ползунок вверх (у меня он в 17 упирается), затем включаем шкалу и ставим шаг 1. И пробуем двигать ползунки. Не двигаются. если кликнуть по шкале ниже ползунков получаем такую картину: минимальное становиться больше максимального 
![image](https://user-images.githubusercontent.com/25764783/71017109-b2c6c180-2128-11ea-8535-9fed7b34a18d.png)

**Comment by Frolikow** [comment]
1. почти готово. Сейчас при действиях описанных выше все работает, но ползунки ставятся в одну позицию, что не логично для слайдера с включенным диапазоном. Логичным будет ставить один ползунок к краю, а второй на расстоянии `step` от него
2. Ничего не изменилось в работе слайдера. Баг все еще присутствует. Что странно, так это то, что данный баг только на втором слайдере. 
Но на других свои проблемы. Например если первый сделтаь вертикальным, поставить шаг 1, то максимальное значение можно выбрать 499 а не 500, а минимум для второго ползунка ставиться 102 вместо 101. Плюс к этому происходит наложение ползунков
![image](https://user-images.githubusercontent.com/25764783/71524837-d7c5ec00-2901-11ea-9a8e-06f63bcb62cb.png)

**Comment by dindeni** [comment]
1. Чтобы не слипались лейблы при малом шаге сделал, чтобы отображались на расстоянии размера лейбла.

**Comment by Frolikow** [comment]
Один момент упустили. По заданию должна быть возможность отключать тултип над ползунком. Это просто делается, думаю проблем не возникнет. 
![image](https://user-images.githubusercontent.com/25764783/72866119-d4f5c580-3d0c-11ea-9ece-bba6aadc65fb.png)
