### ISSUE TITLE
Файловая структура проекта

### ISSUE THREAD

**Issue by imin314** [dindeni/slider#21]
Нужно из папки blocks вынести все, что не является компонентом. Например, шрифты, common, mixins, error по сути тоже не является компонентом, а скорее миксином scss.

Сейчас в папке demo лежат Panel.ts и DemoPage.ts, не связанные ни с каким компонентом. Но на демо-странице архитектура тоже должна быть компонентной.
![Выделение_435](https://user-images.githubusercontent.com/40715953/85271440-02ee5a00-b4a5-11ea-81e3-3214b5664032.png)

**Comment by dindeni** [comment]
Error теперь полноценный компонент, поэтому остался.
