### ISSUE TITLE
Компонент slider

### ISSUE THREAD

**Issue by imin314** [dindeni/slider#22]
У тебя есть компонент slider, в котором ты создаешь элементы thumb, track:
https://github.com/dindeni/slider/blob/0c27580d60d658f8c504356fb1ea37a9f909e4b3/src/blocks/slider/slider.pug#L1-L4

Действительно ли нужно дублировать разметку, которую умеет создавать сам плагин?
https://github.com/dindeni/slider/blob/0c27580d60d658f8c504356fb1ea37a9f909e4b3/src/slider/views/View/View.ts#L246-L252

**Comment by dindeni** [comment]
Удалил элементы до этого issue в #18
