### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by imin314** [dindeni/slider#28]
Нужно поправить размещение импортов по стандартам:
![Выделение_561](https://user-images.githubusercontent.com/40715953/89516167-4e18be00-d802-11ea-864e-2ba2ce4b1352.png)

**Comment by SigidinIlya** [comment]
Проверь глобально плз 
![image](https://user-images.githubusercontent.com/70949093/93723515-b4d21b00-fba7-11ea-8412-a4c75c42ad1a.png)

**Comment by SigidinIlya** [comment]
![image](https://user-images.githubusercontent.com/70949093/96202580-46933500-0f68-11eb-92de-82cd42da34c1.png)
Вот эта конструкция выглядит пугающе, можешь объяснить, зачем здесь отключать эвент mouseup, а затем сразу же его накладывать снова ?

**Comment by SigidinIlya** [comment]
По нашим стандартам, необходимо избегать возможные разрастания функций, и делить их на более понятные, лаконичные решения. К примеру, возьмём метод changeZIndex:
![image](https://user-images.githubusercontent.com/70949093/97920578-b546ff80-1d6a-11eb-9d2f-9607f9b33b9b.png)
Метод получился очень объёмный, во первых при каждом движении мыши у тебя здесь происходит поиск 2 элементов по селектору, в данном случае конечно у тебя ничего лагать не будет, но это не самая быстрая и полезная операция:
![image](https://user-images.githubusercontent.com/70949093/97920665-d6a7eb80-1d6a-11eb-855f-97e51d4b8600.png)
у тебя же есть инстансы этих лейблов? Лучше используй их для того чтобы получить соответствующие html элементы.

Так же вот этот блок:
![image](https://user-images.githubusercontent.com/70949093/97921002-59c94180-1d6b-11eb-801d-32885c919c56.png)
его можно вынести в небольшой приватный метод

**Comment by SigidinIlya** [comment]
По поводу объёмности методов лучше глобально проверь. Подобные варианты - не исключение )
![image](https://user-images.githubusercontent.com/70949093/97921963-c4c74800-1d6c-11eb-97c1-20810efef3c5.png)

**Comment by SigidinIlya** [comment]
Это уже относится к константам, а для констант лучше определить отдельный файл и создать соответствующие переменные, с соответствующими именами, к примеру:
const VALIDATE_VALUE = 'VALIDATE_VALUE' и т.д...
![image](https://user-images.githubusercontent.com/70949093/97922953-51263a80-1d6e-11eb-9582-05c615d5ac3f.png)

**Comment by SigidinIlya** [comment]
Как я вижу, ты немного поменял метод, но сейчас он в контроллере выглядит так:
![image](https://user-images.githubusercontent.com/70949093/99318286-78096400-2878-11eb-89c6-a5540f0fa840.png)

Значения ключей 'type' из метода subscribe вполне тянут на звание констант, для них можно создать соответствующий Enum. Поправь плз исходя из правил именования констант)

**Comment by SigidinIlya** [comment]
Нет необходимости каждый раз объявлять константы.

![image](https://user-images.githubusercontent.com/70949093/100556280-4cdc3700-32b2-11eb-8be3-057c34c605fc.png)

Для этого есть отдельный файл:

![image](https://user-images.githubusercontent.com/70949093/100556297-74330400-32b2-11eb-828d-1d298375e651.png)

И из этого файла уже их экспортировать. Кстати, ключ и значения должны быть зеркальными, к примеру: UPDATE_OPTIONS = 'UPDATE_OPTIONS'
etc...

**Comment by SigidinIlya** [comment]
Все публичные методы и свойства классов должны быть сверху, а снизу приватные. Проверь глобально плз. 

![image](https://user-images.githubusercontent.com/70949093/101811609-59228880-3b2b-11eb-8872-6fed7c1badaa.png)

**Comment by mglknFSD** [comment]
Неиспользуемые переменные лучше переименовать в underscore ("_"), что бы подчеркнуть их неиспользуемость в этом куске кода.

![no_used_vars](https://user-images.githubusercontent.com/75975369/103154865-c7ae4a00-47ab-11eb-9104-1a3278b94cb6.png)
