### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by imin314** [dindeni/slider#29]
В проекте сейчас немного запутанная система типов. В плагин приходят опции в таком виде:
![image](https://user-images.githubusercontent.com/40715953/89516422-9f28b200-d802-11ea-9743-e2bb5ba71790.png)

Но при этом SliderOptions - это интерфейс, который наследует от Slider. Тот в свою очередь еще наследует от ExtremumOptions, RangeAndVerticalOptions. 

В основном интерфейсе Slider избыточное наследование. Пускай в нем будут и min, max, vertical, range тоже. А потом, где надо, ты можешь вытащить нужны свойства с помощью Pick<Slider, 'min' | 'max'>, например.

В дефолтных настройках, кстати, можно не указывать undefined параметры. И почему step по умолчанию не задается?

**Comment by dindeni** [comment]
По умолчанию минимальная функциональность, поэтому нет step

**Comment by SigidinIlya** [comment]
![image](https://user-images.githubusercontent.com/70949093/93722793-037cb680-fba2-11ea-9503-fdab731e2339.png)

В таких моментах лучше затипизировать, ожидаемый метод, его аргументы, что возвращает.

![image](https://user-images.githubusercontent.com/70949093/93722923-f8765600-fba2-11ea-9756-41db3215d036.png)

Проверь глобально плз, чтобы не оставалось 'any' типов.

Так же в большинстве файлов у тебя на большом кол-ве параметров отсутствует типизация, в таких моментах typescript автоматически устанавливает их как 'any', рекомендую в tsconfig'e добавить правило "noImplicitAny".

**Comment by SigidinIlya** [comment]
![image](https://user-images.githubusercontent.com/70949093/94494416-d3fc2880-01f7-11eb-882c-25f9466fd5bf.png)

А зачем здесь вот эти записи принудительных кастований к HTMLInputElement? Вообще необходимо избегать принудительных приведений, поэтому проверь глобально плз, в идеале чтобы их вообще не было.

**Comment by SigidinIlya** [comment]
![image](https://user-images.githubusercontent.com/70949093/94494760-9fd53780-01f8-11eb-81f7-9792b53c54be.png)
Все необязательные свойства типа должны быть снизу после обязательных.

![image](https://user-images.githubusercontent.com/70949093/94494850-dc089800-01f8-11eb-96e9-c6ba7bee03c6.png)
Если здесь будет храниться jQuery элемент, то можно использовать с дженериком - JQuery<HTMLElement>, как-то более очевиднее. В случае с полем 'method', как я говорил выше, необходимо избегать обычной записи 'Function'.

**Comment by SigidinIlya** [comment]
/* eslint-disable no-undef */
![image](https://user-images.githubusercontent.com/70949093/94495093-897bab80-01f9-11eb-88b8-92440c5ea5bc.png)


А что здесь делает коммент отключающий eslint правило 'no-undef' ?

**Comment by SigidinIlya** [comment]
![image](https://user-images.githubusercontent.com/70949093/94495378-43731780-01fa-11eb-8a96-2b8ee70e1b02.png)

В  некоторых файлах ещё висит 'any'. Ты можешь воспользоваться поиском в твоём текстовом редакторе по ключевым словам 'any', так же проведи поиск по моему верхнему комментарию с кастованием по ключевому 'as '

**Comment by dindeni** [comment]
"as" убрал, где возможно обойтись без этого.
"Any, Function" убрал в предыдущем коммите(fd9a050). Теперь точно не должно быть.
Экспортирование было такое, чтобы всё вместе экспортировать. Переделал.

**Comment by SigidinIlya** [comment]
![image](https://user-images.githubusercontent.com/70949093/97923012-6602ce00-1d6e-11eb-9206-50b3af37d5b0.png)

Если приходится кастовать типы, значит скорее всего метод не совсем корректно спроектирован. Вообще, почему метод называется updateState, а в реализации он может как устанавливать значения состояния, получать валидный шаг, и т.д ? 

Кстати, по поводу метода setValueState лучше поменять название, это опять же является привязкой вьюхи к какому-то возможному мифическому стейту, остальные 2 методы начинаются с get, но ничего не возвращают, а только устанавливают соответствующие значения, это довольно неочевидно. 

Возможно, если немного пересмотреть реализацию этого метода, получится избавиться от принудительной смены типа ?

**Comment by mglknFSD** [comment]
https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/README.md#1.10

По бест практис рекомендуется всегда избегать неявного приведения типов (в том числе и в предикате)

![if](https://user-images.githubusercontent.com/75975369/103154545-07bffd80-47a9-11eb-86ea-95c855ff422f.png)

**Comment by mglknFSD** [comment]
Проверки содержащие более одного условия
https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/README.md#1.9

![if2](https://user-images.githubusercontent.com/75975369/103154614-93398e80-47a9-11eb-96cb-8ff3119bf7ea.png)

**Comment by mglknFSD** [comment]
Так же стоит избегать вложеных if 

![if](https://user-images.githubusercontent.com/75975369/103205615-ff7fd380-490a-11eb-9f64-72481b302969.png)

Без вложенных if получается более "плоская" структура состояний, которую легче читать.

**Comment by mglknFSD** [comment]
Неиспользуемая переменная.

![unused vars](https://user-images.githubusercontent.com/75975369/103206344-b16bcf80-490c-11eb-976d-8eade1b77e1c.png)
