### ISSUE TITLE
jQuery best practices

### ISSUE THREAD

**Issue by imin314** [dindeni/slider#30]
В требованиях написано, что плагин должен реализовывать best practices по созданию jQuery плагинов.
Как минимум, не хватает того, чтобы плагин возвращал this (сейчас почему-то возвращаются опции);

Можно вот [тут](https://www.smashingmagazine.com/2011/10/essential-jquery-plugin-patterns/) посмотреть (правда статья не свежая).

**Comment by SigidinIlya** [comment]
по best practices необходимо добавить возможность инициализировать слайдер, используя data атрибуты, в качестве стандартных значений.
