### ISSUE TITLE
Именование

### ISSUE THREAD

**Issue by imin314** [dindeni/slider#31]
Булевые переменные надо именовать так, чтобы в названии заключался вопрос с ответом "да" или "нет".
Настройки range, vertical, label, progress не отвечают этому требованию. Можно добавить предлог with в названии к label и progress. Остальные параметры, наверное, лучше назвать через is..: isVertical, isRange.

**Comment by SigidinIlya** [comment]
![image](https://user-images.githubusercontent.com/70949093/96201927-8822e080-0f66-11eb-8b72-87c08afaa913.png)
Вот этот метод из вьюхи лучше переименовать, т.к по названию может показаться что идёт взаимодействие со state, а вьюха не должна знать о state, таким образом мы исключим связанность слоёв

**Comment by SigidinIlya** [comment]
![image](https://user-images.githubusercontent.com/70949093/96202149-2616ab00-0f67-11eb-89d1-2f25ab36ea61.png)
![image](https://user-images.githubusercontent.com/70949093/96202183-3af33e80-0f67-11eb-9bfa-d52cb9b940e4.png)

в подобных именованиях нет смысла, потому что по данному класу ясно что мы взаимодействуем с thumb'ом, иначе в случае обращения из главной вьюхи это будет выглядить примерно так: 'this.thumb.createThumb()' что не совсем корректно. Проверь глобально этот момент плз.

**Comment by SigidinIlya** [comment]
![image](https://user-images.githubusercontent.com/70949093/96202368-ac32f180-0f67-11eb-9b40-cf681e0a24f2.png)
Не используй цифры в названиях переменных

**Comment by SigidinIlya** [comment]
![image](https://user-images.githubusercontent.com/70949093/97924325-8764b980-1d70-11eb-9fe9-a80de7c9c662.png)
Не используй цифры в именованиях переменных)
А почему labelView имеет метод 'calculateSliderValue', если она что-то вычисляет для слайдера, то она не должна этого делать, если эти вычисления необходимы только для неё, то метод стоит переименовать

**Comment by SigidinIlya** [comment]
Тогда здесь скорее всего по аналогии лучше было бы назвать 'isScaleItemElement'

![image](https://user-images.githubusercontent.com/70949093/101814712-938e2480-3b2f-11eb-9afb-24f4cbcca4bd.png)

**Comment by SigidinIlya** [comment]
А чем отличается getDistance от getDistanceOnTrack ?

![image](https://user-images.githubusercontent.com/70949093/101814879-c3d5c300-3b2f-11eb-99a7-6db1fdf51427.png)

**Comment by SigidinIlya** [comment]
В названии таких констант лучше уточнять их принадлежность, ибо у тебя будет большой проект, там может быть 20 переменных с именами 'UPDATE, VALIDATE, CHECK и т.д' и ты скорее всего запутаешься.

![image](https://user-images.githubusercontent.com/70949093/101814926-d819c000-3b2f-11eb-9940-a5e767dee73a.png)

**Comment by dindeni** [comment]
Теперь getDistanceOnTrack - после клика по треку, getDistanceOnScaleItem - после клика по шкале
