### ISSUE TITLE
Контроллер

### ISSUE THREAD

**Issue by imin314** [dindeni/slider#32]
Метод getPublicData нужен, чтобы передать внешнему коду текущие параметры слайдера? Это неправильно, что он не только вызывает method, но и возвращает настройки слайдера вместе с методом reload. 

Также непонятно, какие методы вообще есть в плагине.

![Выделение_565](https://user-images.githubusercontent.com/40715953/89519247-3fcca100-d806-11ea-9bcc-ec4a0b5ffea2.png)

Нужно в jQuery обертке написать конкретные методы, которые можно вызывать из внешнего кода, и в этих методах (или в соответствующих методах контроллера) вызывать обновление слайдера при необходимости.

**Comment by imin314** [comment]
Контроллер не должен хранить текущие настройки слайдера - это должна делать модель.
https://github.com/dindeni/slider/blob/d874de7bb7dcf8571f07e8e95cbee4de8a96b591/src/slider/Controller/Controller.ts#L21

**Comment by SigidinIlya** [comment]
Почему у тебя метод updateState возвращает undefined ? 
'undefined' скорее подходит для неожиданного результата. Можешь возвращать null | void.
