### ISSUE TITLE
MVC

### ISSUE THREAD

**Issue by imin314** [dindeni/slider#34]
Прежде чем дальше проверять, думаю, стоит обсудить текущую архитектуру проекта.

Чтобы реализовать MVC, нужно разделить логику приложения на 3 слоя:
1) Модель. Хранит текущее состояние слайдера (только то, что относится к бизнес-логике, а не к DOM). В конструкторе модель принимает исходные настройки, валидирует их и предоставляет публичные методы для доступа к ним. Само текущее состояние должно быть приватным. Также модель абстрагирована от представления - она ничего не может знать о координатах и еще каких-либо значениях из вьюхи.

2) Вид. Может знать о модели, чтобы получать текущие параметры (например, максимум или минимум слайдера, показывать ли тултип и т.п). В этом задании нужно декомпозировать вид на несколько "компонентов". То есть у тебя должны быть главная вьюха, которая распределяет работу между дочерними видами, и LabelView, HandleView, ScaleView, ProgressView, TrackView (сама полоска слайдера). Все дочерные виды должны иметь схожие интерфейсы: методы создания DOM, обработчики DOM-событий, методы изменения, собственные события при необходимости. Главный вид - сам не генерит никакой DOM, а только создает нужные экземпляры второстепенных вьюх и вызывает их методы. Также он подписывается на их события через subscribe, чтобы оповестить контроллер о том, что в виде что-то произошло (через notify).

3) Контроллер просто подписывается на события от вида и модели и в ответ вызывают соответствующие методы из вида (для событий модели) и методы модели для событий вида.

Для лучшего понимания опишу еще схему взаимодействия классов, когда пользователь нажимает на бегунок:
HandleView слушает 'mousedown' и, когда оно происходит, начинает слушать 'mousemove' и 'mouseup'. Также он оповещает главную вьюху о произошедших событиях через кастомные события. Например, HandleMouseDown (кстати, handle - не очень удачное название из-за того, что оно часто используется в контексте обработчиков событий). 
Также HandleView передает главной вьюхе коэффициент для расчета нового значения модели или можно на самом деле сразу значение в HandleView посчитать.
Главная вьюха ловит HandleMouseMove и отправляет новое значение в своем кастомном событии. Контроллер ловит его и отправляет новое значение в метод модели, например, setValue(value: number). Модель проверяет новое значение, обновляет свое состояние и выпускает событие ValueChanged, контроллер в ответ вызывает метод главной вьюхи updateView(newValue). В updateView уже вызываются нужные методы HandleView, ProgressView для перемещения прогресс бара и бегунка.

Аналогично с изменениями других настроек модели - можно написать метод, чтобы можно было в модели снаружи изменить размер шага, направление и т.д. (пускай это будет один метод, который принимает на вход строковое название параметры и новое значение). Когда значение изменится, модель выпустит событие OptionChanged, а контроллер при необходимости обновит вид. Также, чтобы из стороннего кода можно было получить доступ к этому событию, надо в jQuery плагине добавить возможность подписаться на это событие через контроллер.

Давай здесь обсудим всё, чтобы вопросов по архитектуре не осталось.

**Comment by imin314** [comment]
Класса ViewUpdating не должно быть - часть логики в нем (например, проверка нового значение на соответствие шагу) должна быть в модели. Другая (изменение стилей бегунков) уйдет в соответствующие дочерние виды.

Вот такие конструкции из условных операторов совсем нечитабельные:
![image](https://user-images.githubusercontent.com/40715953/89526276-aefbc280-d811-11ea-93ad-f9864c45b9f2.png)

И тут еще проверяется как раз бизнес-логика, но только на пикселях. Нужно чтобы вид отправлял просто "сырое" значение, а модель уже сама сравнивала его с шагом, максимумом, минимумом, вторым значением и отправляла в контроллер "чистое" значение.

**Comment by dindeni** [comment]
Теперь view отправляет событие в контролер, в котором вызывается метод модели, после отработки метода, модель оповещает контролер и передает туда проверенные данные и контролер уже отправляет во view результат.

**Comment by SigidinIlya** [comment]
У тебя в главной вьюхе хранятся опции второстепенных вьюх, хотя она должна заниматься только их связанностью. Так же второстепенные вьюхи должны быть самодостаточными Поэтому вот такие моменты лучше ограничить 
![image](https://user-images.githubusercontent.com/70949093/96201139-704a5d00-0f64-11eb-9811-9dcf52868d40.png)

И если какая-то вьюха хочет получить  данные о соседней, то для этого должен быть какой-то соответствующий интерфейс из главной.

**Comment by SigidinIlya** [comment]
Честно говоря до конца не понимаю зачем нужен класс HandleView, по моим ощущениям, он собрал в себе в кучу всё то, что должны хранить соответствующие вьюхи, к примеру здесь происходит навешивание обработчика на thumbElement, но компонент ThumbView должен быть самодостаточным, и в себе хранить все обработчики и взаимодействие с ними, после чего он может выпускать соответствующие эвенты.
![image](https://user-images.githubusercontent.com/70949093/99319561-c4ee3a00-287a-11eb-9bd5-00d89f4ea7c2.png)

**Comment by dindeni** [comment]
Теперь остались только методы связанные с resize и reload, они не относятся к другим дочерним view, поэтому сам класс оставил

**Comment by SigidinIlya** [comment]
window resize методы можешь переместить в главную вьюху, а вот по поводу метода getValue, если я правильно понял, он получает текущие значения слайдера, но у тебя в каждой из LabelView есть public labelValue, этим свойством из инстанса можно пользоваться. Соответственно после этого класс HandleView станет пустым, и его можно удалить.
