### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by Frolikow** [dindeni/slider#4]
на БЭМ-блоках нельзя использовать внешнюю геометрию. Марджины запрещены, паддинги допустимы в редких случаях, когда отступ дополняет блок) т.е. если блок использовать в другом месте - этот отступ должен быть уместен

**Comment by dindeni** [comment]
Исправил насколько понял issue.

**Comment by Frolikow** [comment]
Вроде правильно понял, но осталось пара моментов.

здесь ты и отступы с блока не убрал, и блок стилизуешь в стилях другого блока
![image](https://user-images.githubusercontent.com/25764783/69659636-3274e980-10b1-11ea-8ce9-a951116d6a8a.png)
