### ISSUE TITLE
Linter

### ISSUE THREAD

**Issue by mglknFSD** [dindeni/slider#41]
Пожалуйста, cделай команду для линтера в package.json.

**Comment by mglknFSD** [comment]
Было бы здорово исправить ошибки линтера.

![lint_errors](https://user-images.githubusercontent.com/75975369/104158474-7c787600-53fe-11eb-819f-b56d6a01dbf7.png)

**Comment by dindeni** [comment]
В локальной версии не появлялись почему-то. Теперь должно быть чисто
