### ISSUE TITLE
аргументы функций

### ISSUE THREAD

**Issue by Frolikow** [dindeni/slider#5]
Передачу аргументов в методы - лучше делать объектами а не подобными списками:
```js 
   initSlider(this, config.progress, config.min, config.max, config.label,
      config.step, config.vertical, config.range);
```
во-первых будет лучше читаться - передал объект и внутри функции его деструктурировал. 
во-вторых отпадает необходимость строго соблюдать порядок аргументов, кинул объект и не думаешь что там первое должно быть и что не первое))

**Comment by Frolikow** [comment]
Здесь же дополню сразу, что внутри функции когда будешь принимать объект - заодно сможешь избавиться от подобного:
![image](https://user-images.githubusercontent.com/25764783/70459986-ec277d80-1ae7-11ea-9e9c-0773410ea040.png)
куча входящих параметров у тебя внутрь объекта уйдет, а (важно) для типизации этого объекта сделаешь интерфейс)

**Comment by Frolikow** [comment]
подобные места совсем не понял, почему так сделаны. У тебя ведь в проекте я видел уже интерфейсы. 
![image](https://user-images.githubusercontent.com/25764783/71017974-261d0300-212a-11ea-8bca-670288c4c036.png)

В общем я имел ввиду такое решение этой проблемы
![image](https://user-images.githubusercontent.com/25764783/71017841-d9392c80-2129-11ea-9c2d-6598f6301ce7.png)

Проверь по всему проекту, это замечание. И сразу скажу чтоб потом не возвращаться к этому - Если у тебя какой-то интерфейс используется больше 1 раза. То можешь сразу создавать папку types и туда выносить интерфейсы, от туда эксортировать, и импортить там где надо)

**Comment by dindeni** [comment]
Поправил, где повторяются аргументы. В остальных местах аргументы все разные.

**Comment by Frolikow** [comment]
> Проверь по всему проекту, это замечание. И сразу скажу чтоб потом не возвращаться к этому - Если у тебя какой-то интерфейс используется больше 1 раза. То можешь сразу создавать папку types и туда выносить интерфейсы, от туда экспортировать, и импортить там где надо)

так а почему только повторяющиеся интерфейсы вынес? Получается сделал последние два предложения из всего ишью. Понимаешь?

**Comment by dindeni** [comment]
Понял, переделал.
