### ISSUE TITLE
именование и объявления

### ISSUE THREAD

**Issue by Frolikow** [dindeni/slider#6]
1) Объявлять переменные в одну строку - очень плохая практика, сильно мешает чтению кода. Только при деструктуризации такое не мешает чтению
```ts
let widthHeightTrack: number; let thumbMin: HTMLElement; let thumbMax: HTMLElement;
```
2) при именовании не надо делать сокращений, особенно не очевидных. Лучше писать полноценно `event`, иногда допустимо написать `e`
```ts
const changeSlider = (evt: MouseEvent): void => {
```
3) имена переменных нужно стараться подбирать так, чтобы при чтении кода приходилось минимум задываться, что же может значить та или иная переменная. Пример плохого именования: `trackWidthHeight`. Если не изучить окружающий ее код, то догадаться что же это - сложно) ширина? или высота? 

4) Еще пример именования вводящий в ступор `ViewDnD`? за что отвечает эта вьюха?
5) Именование функций. В имени должен присутствовать глагол т.к. функция что-то делает и имя функции должно отображать что она делает. Пример `handlerClick` handler - существительное. 
И сюда же  - именование обработчиков событий довольно четко прописано в стандартах наших, рекомендую освежить в памяти  - прочитать)

**Comment by Frolikow** [comment]
![image](https://user-images.githubusercontent.com/25764783/71018569-544f1280-212b-11ea-91ec-b3a8e685c960.png)
По именованию обработчиков явно не допонял материал) [Стандарты `functionsNaming`](https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/functionsNaming.md)

**Comment by dindeni** [comment]
Как понял, "ElementName - имя БЭМ-элемента", у меня обработчик не на элементе, а на блоке (demo). "Если компонента не вложена в БЭМ-элемент, то ElementName в данном случае стоит выбирать по смыслу, исходя из контекста". Получается handleFormChange.

**Comment by Frolikow** [comment]
> Как понял, "ElementName - имя БЭМ-элемента", у меня обработчик не на элементе, а на блоке (demo). "Если компонента не вложена в БЭМ-элемент, то ElementName в данном случае стоит выбирать по смыслу, исходя из контекста". Получается handleFormChange.

Нет, `ElementName` - имя элемента. В контексте обработчиков точно не важно БЭМ-элемент или БЭМ-блок у тебя. В данном случае у тебя какой-то элемент записан в переменную formElement. Т.е. ты вызываешь обработчик на `formElement`, а не на `Form`. Если бы элемент был form - то логично было бы именовать обработчик как у тебя сейчас.
И кстати тебе не кажется странным, что ты элемент с классом `.js-demo` кладешь в переменную `formElement`? Чтоб понять что это не элемент формы - приходиться ковырятся в коде.

**Comment by dindeni** [comment]
Но класс же на тэге form, поэтому так назвал.

**Comment by Frolikow** [comment]
> Но класс же на тэге form, поэтому так назвал.

Тут надо смотреть на именование именно в контексте js-a. Ты обрабатываешь событие элемента который лежит в переменной formElement. Если обработчик лежит  в этом же файле - глядя на его имя, ты сразу поймешь 
1) что это обработчик
2) на каком элементе он сработал
3) тип события

по обработчикам - сейчас правильно
остальное именование буду смотреть во всем процессе ревью и сюда отписываться что исправить
