### ISSUE TITLE
demoPage.ts

### ISSUE THREAD

**Issue by Frolikow** [dindeni/slider#7]
Тут я вообще не понял) 
есть у тебя класс DemoPage. Судя из названия я ожидал увидеть какую-то оболочку в которой твои слайдры лежат)  но 531 строка кода намекают что это нечто иное)) можешь вкратце описать какую часть плагина выполняет DemoPage? И если он делает что-то важное для плагина(то без чего плагин не будет работать) то почему ты ни разу не упомянул его в ридми?

**Comment by dindeni** [comment]
Тут ошибка, класс не относится к слайдеру. Исправил.

**Comment by Frolikow** [comment]
> Тут ошибка, класс не относится к слайдеру. Исправил.

А к чему относится? 
файл теперь на 700+ строк Оо)) 
Давай все-таки попробуешь вкратце объяснить что делает весь этот класс. Потому что у меня очень большие подозрения что в нем имеется логика которая не должна в нем быть) 
Поэтому лучше чтоб ты объяснил, прежде чем я (возможно ошибочно) буду просить правки.

**Comment by dindeni** [comment]
Частично переписал в issue demo(3f84c33f) теперь не такой большой файл. Создает элементы для демо страницы, отвечает за логику форм, инициализирует плагины и обновляет их, в слайдеры больше не лезет.
